services:
  app:
    container_name: my_project_app
    build: ./
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - ./app:/src/app
    ports:
      - ${POST_DB_HOST}:8000
    restart: always
    env_file:
      - .env
  db:
    container_name: my_project_postgres
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${POST_DB_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/database
    restart: always
